### ISSUE TITLE
Build error on Android

### ISSUE THREAD

**Issue by lukeeey** [mhsjlw/RakNet#2]
```
/sdcard/dev/cpp/Bedrock++/lib/RakNet/src/FileList.cc:24:10: fatal error: 'sys/io.h' file
      not found
#include <sys/io.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [lib/RakNet/CMakeFiles/RakNetStatic.dir/build.make:567: lib/RakNet/CMakeFiles/RakNetStatic.dir/src/FileList.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:88: lib/RakNet/CMakeFiles/RakNetStatic.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

This also happens with the original RakNet library, could probably do with some checks.

**Comment by lukeeey** [comment]
For reference: https://github.com/facebookarchive/RakNet/issues/66

**Comment by lukeeey** [comment]
I also get errors when including the RakNet namespace. I assume i need to include every source file but i'm wondering how to do that without typing it all individually.

```
$ cmake --build .
[ 49%] Built target RakNetStatic
[ 98%] Built target RakNetShared
Scanning dependencies of target bedrock++
[ 99%] Building CXX object src/CMakeFiles/bedrock++.dir/Server.cpp.o
[ 99%] Building CXX object src/CMakeFiles/bedrock++.dir/util/ChatFormat.cpp.o
[100%] Linking CXX executable bedrock++
CMakeFiles/bedrock++.dir/Server.cpp.o: In function `Server::Start(int, char*, int, char*)':
/sdcard/dev/cpp/Bedrock++/src/Server.cpp:(.text+0x1c): undefined reference to `RakNet::RakPeerInterface::GetInstance()'
/sdcard/dev/cpp/Bedrock++/src/Server.cpp:(.text+0x40): undefined reference to `RakNet::SocketDescriptor::SocketDescriptor(unsigned short, char const*)'
CMakeFiles/bedrock++.dir/Server.cpp.o: In function `__cxx_global_var_init':
/sdcard/dev/cpp/Bedrock++/src/Server.cpp:(.text.startup+0x14): undefined reference to `RakNet::SystemAddress::SystemAddress()'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/bedrock++.dir/build.make:147: src/bedrock++] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: src/CMakeFiles/bedrock++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by mhsjlw** [comment]
I plan on pulling in as much as I can from larku and current pull requests from RakNet. May I ask what your use case is and if you're using the static library or shared library?

**Comment by lukeeey** [comment]
Idk i'm trying to just include it using `add_subdirectory`

**Comment by mhsjlw** [comment]
Ah, yeah. That won't link. I don't believe I am properly exporting the shared and static libraries properly. Let me take a look at your PR then at this problem

**Comment by mhsjlw** [comment]
Ok so, add `target_link_libraries` to your executable and give it the `RakNetShared` library

**Comment by lukeeey** [comment]
What's the benfit of shared over static?

**Comment by mhsjlw** [comment]
https://stackoverflow.com/questions/2649334/difference-between-static-and-shared-libraries

**Comment by lukeeey** [comment]
I dont know why anyone would want to use shared lol

**Comment by mhsjlw** [comment]
No runtime costs and you don't have to ship `.dll`, `.so` or `.dylib` files with your executable. The Rust programming language only uses static compilation for all of it's dependencies, for example. It really just depends what your software is

**Comment by lukeeey** [comment]
Well i don't care anymore i got the server broadcasting to LAN :)

**Comment by mhsjlw** [comment]
https://gitter.im/mhsjlw/RakNet
